vllm_flash_attn/flash_attn_interface.py
This way we can avoid the copy we are currently doing in vLLM.
=> Expose out in python API

csrc/flash_attn/flash_api.cpp
=> Fix out kwarg shape check with ngroups swapped

vllm_flash_attn/flash_attn_interface.py
`torch.compile` (Dynamo) had a difficult time compiling a lambda function (nested function). making it a normal function will ease torch.compile's job.
=> use global function rather than lambda

.github/workflows/publish.yml
FIX issue reported here with vllm-flash-attn blocking vLLM's python upgrade https://github.com/vllm-project/vllm/issues/6877#issuecomment-2257939832
Should be this simple based on the support in flash-attention: https://github.com/Dao-AILab/flash-attention/pull/870/files
=> Adds Python 3.12 to publish.yml

csrc/flash_attn/src/flash_fwd_kernel.h
This fixes a line in `compute_attn_1rowblock_splitkv` kernel function that uses `params.seqlen_k` to use `binfo.actual_seqlen_k` instead to access the seqlen_k value.
This is a fix to the `flash_attn_varlen_func` function producing wrong results when used with cudaGraph over different input parameters, as found in this vLLM PR (https://github.com/vllm-project/vllm/pull/6052).
=> Fix a wrong reference to seqlen_k variable in the varlen kernel

csrc/flash_attn/flash_api.cpp
This is a cherry pick of https://github.com/Dao-AILab/flash-attention/pull/1085 which fixes an illegal memory access in the splitkv flash attention kernel.
I've done some simple tests and it appears to not break anything.
=> Fix ima for split-kv kernel

cmake/utils.cmake
Use a better method to specify CUDA link libraries so that we can upgrade vLLM to pytorch 2.5.
cc @ProExpertProg, @WoosukKwon, @simon-mo, @youkaichao
=> Use better method to specify cuda libraries

csrc/flash_attn/flash_api.cpp, vllm_flash_attn/flash_attn_interface.py
This PR removes several lines of code in `varlen_fwd` that is irrelevant to the vLLM's usage. Particularly, this change saves two unnecessary `reshape` ops and one `empty` op.
=> Remove redundant code in `varlen_fwd`

tests/test_vllm_flash_attn.py
Simple change to avoid clobbering the query tensor in the reference implementation for paged attention in `test_vllm_flash_attn.py`.
Not a problem in the current tests but potentially confusing.
=> Avoid clobbering query in ref_paged_attn

vllm_flash_attn/flash_attn_interface.py
In Open Source, we assume the build is done by CMake, but there is exceptions. So we cannot always assume vllm_flash_attn_c (the .so) file is in the same folder as flash_attn_interface.py. Instead, we turn this import as optional. Even the import fails, we still keep running the remaining part of the file.
=> Turn import vllm_flash_attn_c into optional in flash_attn_interface.py

csrc/flash_attn/flash_api.cpp
baa5235524cdb0c60ff8a448c802ff575122b986 Lu Fang <lufang@fb.com> Eliminate c10::optional usage in vllm_flash_attn
Otherwise, it may fail the build.
=> Eliminate c10::optional usage in vllm_flash_attn

csrc/flash_attn/src/flash_fwd_kernel.h, csrc/flash_attn/src/utils.h
Fix issue when there is less than `kBlockN / page_size` pages in the final block, in this case we can read off the end of the `block_table`
=> [Bugfix] fix illegal memory access

vllm_flash_attn/flash_attn_interface.py
https://github.com/vllm-project/vllm/issues/13398 observed a strange error message that said the user could use FA2 because FA3 was unsupported.
This PR should fix the error message.
=> Fix typo in `fa_version_unsupported_reason`

hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp
Fix building on CUDA 12.1 which was failing with:
```
[2025-02-14T20:12:40Z] #27 4842.4 /workspace/.deps/vllm-flash-attn-src/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp(1068): error: no operator "=" matches these operands
[2025-02-14T20:12:40Z] #27 4842.4             operand types are: cutlass::bfloat16_t = float
[2025-02-14T20:12:40Z] #27 4842.4                       sScale(get<0>(taccOcO_row(mi)), stage) = scales(mi);
```
=> Fix building on CUDA 12.1

CMakeLists.txt
This PR adds Blackwell archs and updates the CUTLASS version.
=> adding preliminary Blackwell support

CMakeLists.txt
This matches the work done in https://github.com/vllm-project/flash-attention/commit/88786928edeecf647cc1aca29f95eeda4a6eacea Python 3.8 was subsequently dropped as well here.
Related to https://github.com/vllm-project/vllm/pull/13164
=> Add python 3.13 support to CMakeLists.txt

csrc/common/pytorch_shim.h, csrc/flash_attn/flash_api_sparse.cpp, csrc/flash_attn/flash_api_torch_lib.cpp
Seeing build issues on this. c10::optional is being deprecated.
This is similar issue addressed in https://github.com/vllm-project/vllm/pull/11730.
Run this e2e internally.
=> [Easy] replace c10::optional with std::optional

csrc/flash_attn/flash_api_sparse.cpp
Cherry-picked hotfix from [https://github.com/vllm-project/flash-attention/pull/39](https://github.com/vllm-project/flash-attention/pull/39) originally by @minminsun which includes critical bug fixes for sparse attention kernel window size.  Original PR was closed since the files in this fork were synced with upstream. Notably, the [dual-chunk attention PR in vLLM](https://github.com/vllm-project/vllm/pull/11844) requires this fix.
=> Sparse attention window size bug fix

hopper/flash_api.cpp, hopper/flash_fwd_launch_template.h, hopper/heuristics.h, hopper/tile_size.h
Boost decode performance by using only 1 mma warp group to reduce wasted compute (i.e. use kBlockM == 64 instead of 128)
```
FlashAttn vs FlashInfer Timing (ms)                           
┏━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━┳━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ Type   ┃ Name        ┃ S     ┃ P  ┃ FlashAttn (ms) ┃ FlashInfer (ms) ┃ (FA-FI)/FI (%) ┃
┡━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━╇━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━┩
│ decode │ qwen32b-tp2 │ 1024  │ 1  │ 0.0148         │ 0.0123          │ 20.30          │
│ decode │ qwen32b-tp2 │ 2048  │ 1  │ 0.0156         │ 0.0142          │ 9.39           │
│ decode │ qwen32b-tp2 │ 4096  │ 1  │ 0.0165         │ 0.0159          │ 3.78           │
│ decode │ qwen32b-tp2 │ 8192  │ 1  │ 0.0191         │ 0.0188 …
```
=> FA3 Decode Perf - Use single mma warp group for decode batches 

CMakeLists.txt, cmake/utils.cmake
NOTE: cmake changes lifted from https://github.com/vllm-project/vllm/pull/18155
Helps with wheel size, not seeing any performance degradation on Blackwell once the cache is warmed up 
See https://github.com/vllm-project/vllm/pull/19336 for more details
=> FA2 8.0 PTX

vllm_flash_attn/flash_attn_interface.py
fix 
```
RuntimeError: _vllm_fa2_C::varlen_fwd() expected at most 21 argument(s) but received 22 argument(s). Declaration: _vllm_fa2_C::varlen_fwd(Tensor($0! -> ) q, Tensor k, Tensor v, Tensor($1! -> )? out, Tensor cu_seqlens_q, Tensor cu_seqlens_k, Tensor? seqused_k, Tensor? leftpad_k, Tensor? block_table, Tensor? alibi_slopes, int max_seqlen_q, int max_seqlen_k, float p_dropout, float softmax_scale, bool zero_tensors, bool is_causal, int window_size_left, int window_size_right, float softcap, bool return_softmax, Generator? gen) -> Tensor[]
```
introduced in https://github.com/vllm-project/flash-attention/pull/75
=> [BugFix] Fix FA2 RuntimeError when sinks is provided

vllm_flash_attn/flash_attn_interface.py
Trying to run the hybrid models test is giving me grief without this change:
```
python -m pytest models/language/generation/test_hybrid.py::test_models[5-64-ai21labs/Jamba-tiny-dev] -xsv
```
produces:
```
models/language/generation/test_hybrid.py:97: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:788: in __init__
self.llm = LLM(
../vllm/entrypoints/llm.py:277: in __init__
self.llm_engine = LLMEngine.from_engine_args(
../vllm/engine/llm_engine.py:494: in from_engine_args
return engine_cls.from_vllm_config(
../vllm/engine/llm_engine.py:470: in from_vllm_config
return cls(
../vllm/engine/llm_engine.py:263: in __init__ …
```
=> Pass s_aux through flash_attn_with_kvcache
